### ISSUE TITLE
Using training script

### ISSUE THREAD

**Issue by DMAgit** [lorenzo-stacchio/stable-diffusion_custom_inpaint#3]
Hey, has anyone been able to use the training script? I tried both on my own data and on the images in the `INPAINTING` folder. I create a dataloader csv as described, but when running the model I get the following error. 

Does anyone have pointers? Or at least a direction for me to look in, as the Python debugger is very unhappy when it starts going into the torch files. 

I'd be thrilled at a reply :)

```
  File "-/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 512, 3, 512] to have 3 channels, but got 512 channels instead
None
```

###Full output:
```
python3 main_inpainting.py --train --name desktop --base configs/latent-diffusion/inpainting_training_dma_desktop.yaml --gpus 0, --seed 42 
Global seed set to 42
[{'model': {'base_learning_rate': 0.0001, 'target': 'ldm.models.diffusion.ddpm.LatentInpaintDiffusion', 'params': {'linear_start': 0.0015, 'linear_end': 0.0205, 'num_timesteps_cond': 1, 'log_every_t': 100, 'timesteps': 1000, 'loss_type': 'l1', 'first_stage_key': 'image', 'cond_stage_key': 'masked_image', 'cond_stage_trainable': False, 'image_size': 128, 'channels': 3, 'concat_mode': True, 'monitor': 'val/loss', 'ckpt_path': 'models/ldm/inpainting_big/model_compvis.ckpt', 'scheduler_config': {'target': 'ldm.lr_scheduler.LambdaLinearScheduler', 'params': {'warm_up_steps': [10000], 'cycle_lengths': [10000000000000], 'f_start': [1e-06], 'f_max': [1.0], 'f_min': [1.0]}}, 'unet_config': {'target': 'ldm.modules.diffusionmodules.openaimodel.UNetModel', 'params': {'image_size': 64, 'in_channels': 7, 'out_channels': 3, 'model_channels': 256, 'attention_resolutions': [8, 4, 2], 'num_res_blocks': 2, 'channel_mult': [1, 2, 3, 4], 'num_heads': 8, 'resblock_updown': True, 'use_checkpoint': True}}, 'first_stage_config': {'target': 'ldm.models.autoencoder.VQModelInterface', 'params': {'embed_dim': 3, 'n_embed': 8192, 'monitor': 'val/rec_loss', 'ddconfig': {'attn_type': 'none', 'double_z': False, 'z_channels': 3, 'resolution': 256, 'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult': [1, 2, 4], 'num_res_blocks': 2, 'attn_resolutions': [], 'dropout': 0.0}, 'lossconfig': {'target': 'torch.nn.Identity'}}}, 'cond_stage_config': '__is_first_stage__'}}, 'data': {'target': 'main_inpainting.DataModuleFromConfig', 'params': {'batch_size': 2, 'num_workers': 1, 'wrap': False, 'train': {'target': 'ldm.data.inpainting.InpaintingTrain', 'params': {'csv_file': 'desktop_data.csv', 'data_root': 'data/INPAINTING/custom_inpainting', 'size': 512}}, 'validation': {'target': 'ldm.data.inpainting.InpaintingValidation', 'params': {'csv_file': 'desktop_data.csv', 'data_root': 'data/INPAINTING/custom_inpainting', 'size': 512}}}}, 'lightning': {'find_unused_parameters': False, 'callbacks': {'image_logger': {'target': 'main_inpainting.ImageLogger', 'params': {'disabled': False, 'batch_frequency': 750, 'max_images': 4, 'increase_log_steps': True, 'log_first_step': True, 'log_images_kwargs': {'use_ema_scope': False, 'plot_progressive_rows': True, 'plot_diffusion_rows': True, 'N': 4, 'unconditional_guidance_scale': 1.0, 'unconditional_guidance_label': [''], 'ddim_steps': 50, 'ddim_eta': 0.0}}}}}}]
Running on GPUs 0,
LatentInpaintDiffusion: Running in eps-prediction mode
DiffusionWrapper has 387.25 M params.
Keeping EMAs of 418.
making attention of type 'none' with 512 in_channels
Working with z of shape (1, 3, 64, 64) = 12288 dimensions.
making attention of type 'none' with 512 in_channels
Using first stage also as cond stage.
modifying key 'model.diffusion_model.input_blocks.0.0.weight' and keeping its original 7 (channels) dimensions only
modifying key 'model.diffusion_model.input_blocks.0.0.weight' and keeping its original 7 (channels) dimensions only
Restored from models/ldm/inpainting_big/model_compvis.ckpt with 0 missing and 4 unexpected keys
Unexpected Keys: ['ddim_sigmas', 'ddim_alphas', 'ddim_alphas_prev', 'ddim_sqrt_one_minus_alphas']
Monitoring val/loss as checkpoint metric.
Merged modelckpt-cfg: 
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/2023-02-08_desktop/checkpoints', 'filename': '{epoch:06}', 'mode': 'min', 'verbose': True, 'save_last': True, 'monitor': 'val/loss', 'save_top_k': 1}}
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
#### Data #####
train, InpaintingTrain, 1
validation, InpaintingValidation, 1
accumulate_grad_batches = 1
++++ NOT USING LR SCALING ++++
Setting learning rate to 1.00e-04
Global seed set to 42
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
----------------------------------------------------------------------------------------------------
distributed_backend=nccl
All DDP processes registered. Starting ddp with 1 processes
----------------------------------------------------------------------------------------------------

-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py:423: LightningDeprecationWarning: DataModule.setup has already been called, so it will not be called again. In v1.6 this behavior will change to always call DataModule.setup.
  rank_zero_deprecation(
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Setting up LambdaLR scheduler...
Lightning config
find_unused_parameters: false
callbacks:
  image_logger:
    target: main_inpainting.ImageLogger
    params:
      disabled: false
      batch_frequency: 750
      max_images: 4
      increase_log_steps: true
      log_first_step: true
      log_images_kwargs:
        use_ema_scope: false
        plot_progressive_rows: true
        plot_diffusion_rows: true
        'N': 4
        unconditional_guidance_scale: 1.0
        unconditional_guidance_label:
        - ''
        ddim_steps: 50
        ddim_eta: 0.0
trainer:
  accelerator: ddp
  deterministic: true
  gpus: 0,


  | Name              | Type             | Params
-------------------------------------------------------
0 | model             | DiffusionWrapper | 387 M 
1 | model_ema         | LitEma           | 0     
2 | first_stage_model | VQModelInterface | 53.2 M
-------------------------------------------------------
387 M     Trainable params
53.2 M    Non-trainable params
440 M     Total params
1,761.861 Total estimated model params size (MB)
Validation sanity check: 0it [00:00, ?it/s]-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py:105: UserWarning: The dataloader, val dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 64 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
Validation sanity check:   0%|                                                                                       | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main_inpainting.py", line 707, in <module>
    trainer.fit(model, data)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_train
    self._run_sanity_check(self.lightning_module)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1115, in _run_sanity_check
    self._evaluation_loop.run()
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 110, in advance
    dl_outputs = self.epoch_loop.run(
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 110, in advance
    output = self.evaluation_step(batch, batch_idx, dataloader_idx)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 154, in evaluation_step
    output = self.trainer.accelerator.validation_step(step_kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 211, in validation_step
    return self.training_type_plugin.validation_step(*step_kwargs.values())
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 386, in validation_step
    return self.model(*args, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 963, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File -/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "-/stable-diffusion_custom_inpaint/ldm/models/diffusion/ddpm.py", line 378, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "-/stable-diffusion_custom_inpaint/ldm/models/diffusion/ddpm.py", line 888, in shared_step
    x, c = self.get_input(batch, self.first_stage_key)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "-/stable-diffusion_custom_inpaint/ldm/models/diffusion/ddpm.py", line 1539, in get_input
    z, c, x, xrec, xc = super().get_input(batch, self.first_stage_key, return_first_stage_outputs=True,
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "-/stable-diffusion_custom_inpaint/ldm/models/diffusion/ddpm.py", line 682, in get_input
    encoder_posterior = self.encode_first_stage(x)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "-/stable-diffusion_custom_inpaint/ldm/models/diffusion/ddpm.py", line 885, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "-/stable-diffusion_custom_inpaint/ldm/models/autoencoder.py", line 270, in encode
    h = self.encoder(x)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "-/stable-diffusion_custom_inpaint/ldm/modules/diffusionmodules/model.py", line 441, in forward
    hs = [self.conv_in(x)]
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "-/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [128, 3, 3, 3], expected input[1, 512, 3, 512] to have 3 channels, but got 512 channels instead
None

```

**Comment by DMAgit** [comment]
And the config I am using, though it's just the reference file with the directories changed:

```
model:
  # base_learning_rate: 1.0e-06
  base_learning_rate: 1.0e-04

  target: ldm.models.diffusion.ddpm.LatentInpaintDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000 # per overfittare tutti i livelli di rumore almeno 500 epoche
    loss_type: l1
    first_stage_key: image
    cond_stage_key: masked_image # 4 channels
    cond_stage_trainable: false 
    # image_size: 64 # feature map size
    # QUESTO DECIDE LA SIZE DEL RUMORE, QUA E' NECESSARIA METTERLA A 128 PERCHE' IN INFERENCE NORMALE NON VIENE UTILIZZATA MA DAL LOGGER SI
    image_size: 128 # feature map size for 512 ---> l'hanno lasciata a 64 perchè loro hanno addestrato su 256? però in inference questo non viene minimamente usato, solo nei logger
    channels: 3
    concat_mode: true # there will be no context_dim specified in unet,
    # check configs/stable-diffusion/v1-inference.yaml for cross-attention adn context dim
    monitor: val/loss
    #monitor: val/loss_simple_ema
    # scale_factor: 0.18215
    ckpt_path: "models/ldm/inpainting_big/model_compvis.ckpt"
    
    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 10000 ] # NOTE for resuming 2500. use 10000 if starting from scratch
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64 # unused
        in_channels: 7 # image, masked image, mask
        out_channels: 3 #FINAL IMAGE
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
        use_checkpoint: True # gradient checkpointing
        # legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          attn_type: none # concat mode
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity # NO TRAIN FOR AUTOENCODER
    cond_stage_config: __is_first_stage__

data:
  target: main_inpainting.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 1
    wrap: false
    train:
      target: ldm.data.inpainting.InpaintingTrain
      params:
        csv_file: "desktop_data.csv"
        data_root: "data/INPAINTING/custom_inpainting"
        size: 512
    validation:
      target: ldm.data.inpainting.InpaintingValidation
      params:
        csv_file: "desktop_data.csv"
        data_root: "data/INPAINTING/custom_inpainting"
        size: 512


lightning:
  find_unused_parameters: False

  callbacks:
    image_logger:
      target: main_inpainting.ImageLogger
      params:
        disabled: False
        batch_frequency: 750
        max_images: 4
        increase_log_steps: True
        log_first_step: True
        log_images_kwargs:
          use_ema_scope: False
          plot_progressive_rows: True
          plot_diffusion_rows: True
          N: 4
          unconditional_guidance_scale: 1.0
          unconditional_guidance_label: [""]
          ddim_steps: 50  # todo check these out for inpainting,
          ddim_eta: 0.0   # todo check these out for inpainting,
  # trainer:
  #   benchmark: True
  #   val_check_interval: 5000000  # really sorry
  #   num_sanity_val_steps: 0
  #   accumulate_grad_batches: 2
```
